accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import signup

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("signup/", signup, name="signup"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
    path("reciepts/", include("reciepts.urls")),
]

reciepts/urls.py
from django.urls import path
from reciepts.views import (
    RecieptListView,
    AccountCreateView,
    CategoryCreateView,
    RecieptCreateView,
    AccountListView,
    ExpenseCategoryListView,
)

urlpatterns = [
    path("", RecieptListView.as_view(), name="home"),
    path(
        "accounts/create/", AccountCreateView.as_view(), name="create_account"
    ),
    path(
        "categories/create",
        CategoryCreateView.as_view(),
        name="create_category",
    ),
    path("create", RecieptCreateView.as_view(), name="create_reciept"),
    path("accounts/", AccountListView.as_view(), name="account_list"),
    path(
        "categories/", ExpenseCategoryListView.as_view(), name="category_list"
    ),
]

accounts/models.py
from django.db import models

# Create your models here.

reciepts/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="categories",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="accounts",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Reciept(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(decimal_places=3, max_digits=10)
    tax = models.DecimalField(decimal_places=3, max_digits=10)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="reciepts",
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        "ExpenseCategory", related_name="reciepts", on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        "Account", related_name="reciepts", on_delete=models.CASCADE, null=True
    )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# Create your views here.
def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm(request.POST)
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

reciepts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import TemplateView
from django.views.generic import CreateView, ListView
from reciepts.models import Account, ExpenseCategory, Reciept

# Create your views here.
class RecieptListView(LoginRequiredMixin, ListView):
    model = Reciept
    template_name = "reciepts/list.html"

    def get_queryset(self):
        return Reciept.objects.filter(purchaser=self.request.user)


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "accounts/create.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("account_list")


class CategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "categories/create.html"
    fields = ["name", "owner"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.user_property = self.request.user
        item.save()
        return redirect("category_list")


class RecieptCreateView(LoginRequiredMixin, CreateView):
    model = Reciept
    template_name = "reciepts/create.html"
    fields = [
        "vendor",
        "total",
        "tax",
        "date",
        "purchaser",
        "category",
        "account",
    ]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.user_property = self.request.user
        item.save()
        return redirect("home")


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "accounts/list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "categories/list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)

accounts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'app.css'%}">
    <title>Accounts</title>
</head>

<body>
    <header>
        <nav>
            <ul class="navigation">
                {% if user.is_authenticated %}
                    <li class ="nav-item">
                        <a href= "{% url 'logout'%}">Logout</a>
                    </li>
                    <li class ="nav-item">
                        <a href= "{% url 'home'%}">Reciepts</a>
                    </li>
                    <li class ="nav-item">
                        <a href= "{% url 'create_reciept'%}">Create Receipt</a>
                    </li>
                    <li class ="nav-item">
                        <a href= "{% url 'account_list'%}">Accounts</a>
                    </li>
                    <li class ="nav-item">
                        <a href= "{% url 'create_account'%}">Create Account</a>
                    </li>
                    <li class ="nav-item">
                        <a href= "{% url 'category_list'%}">Categories</a>
                    </li>
                    <li class ="nav-item">
                        <a href= "{% url 'create_category'%}">Create Category</a>
                    </li>
                {%else%}
                    <li class ="nav-item">
                        <a href= "{% url 'login' %}">Login</a>
                    </li>
                    <li class ="nav-item">
                        <a href= "{% url 'signup' %}">Sign Up</a>
                    </li>
                {%endif%}
                
            </ul>
        </nav>
    </header>
    {%block content%}

    {%endblock content%}
</body>

</html>

reciepts/templates/accounts/create.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button>Submit</button>
    </form>
{% endblock content %}

reciepts/templates/accounts/list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Accounts</h1>
    <table>
        <theader> 
            <tr>
                <th>Name</th>
                <th>Number</th>
                <th>Number of Reciepts</th>
            </tr>
        </theader>
        <tbody>
            {%for account in account_list%}
            <tr>
                <td>{{account.name}}</td>
                <td>{{account.number}}</td>
                <td>{{account.reciepts.all|length}}</td>
            </tr>
            {%endfor%}
        </tbody>
    </table>

{% endblock content %}

reciepts/templates/categories/create.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button>Submit</button>
    </form>
{% endblock content %}

reciepts/templates/categories/list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Expense Category</h1>
    <table>
        <theader> 
            <tr>
                <th>Name</th>
                <th>Number of reciepts</th>
            </tr>
        </theader>
        <tbody>
            {%for category in expensecategory_list%}
            <tr>
                <td>{{category.name}}</td>
                <td>{{category.reciepts.all|length}}</td>
            </tr>
            {%endfor%}
        </tbody>
    </table>

{% endblock content %}

reciepts/templates/reciepts/create.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button>Submit</button>
    </form>
{% endblock content %}

reciepts/templates/reciepts/list.html
{%extends 'base.html' %}
{% block content %}
    <h1>Receipts</h1>
    <table>
        <theader> 
            <tr>
                <th>Vendor</th>
                <th>Total</th>
                <th>Tax</th>
                <th>Date</th>
                <th>Category</th>
                <th>Account</th>
            </tr>
        </theader>
        <tbody>
            {%for reciept in reciept_list%}
            <tr>
                <td>{{reciept.vendor}}</td>
                <td>{{reciept.total}}</td>
                <td>{{reciept.tax}}</td>
                <td>{{reciept.date|date:"M-d-Y"}}</td>
                <td>{{reciept.category.name}}</td>
                <td>{{reciept.account.name}}</td>
            </tr>
            {%endfor%}
        </tbody>
    </table>

{% endblock content %}